defaults:
  - data: openmask3d

openmask3d:
  top_k: 5
  multi_level_expansion_ratio: 0.1
  num_of_levels: 3
  vis_threshold: 0.2
  frequency: 10 # not used
  num_random_rounds: 10
  num_selected_points: 5

external:
  sam_checkpoint: '../resources/sam_vit_h_4b8939.pth'
  sam_model_type: 'vit_h'
  clip_model: 'ViT-L/14@336px'

output:
  experiment_name: 'experiment'
  output_directory: 'output/'
  save_crops: False

gpu:
  optimize_gpu_usage: False